blacklist: []
build_space: build
catkin_make_args: []
cmake_args:
- -DCMAKE_TOOLCHAIN_FILE=$ISAAC_WS/src/scripts/build/astrobee_cross.cmake
- -DARMHF_CHROOT_DIR=$ISAAC_WS/arm_cross/rootfs
devel_layout: linked
devel_space: devel
extend_path: $ISAAC_WS/arm_cross/rootfs/opt/astrobee
install: true
install_space: install
isolate_install: false
jobs_args: []
log_space: logs
make_args: []
source_space: src
use_env_cache: false
use_internal_make_jobserver: true
whitelist: []
